#!/usr/bin/env bash
# display list of currently running process
# show all process for all users including those which might not have a TTY
# display in user-oriented format
# show process hierachy

ps -axjf
