#!/usr/bin/env bash

# Display PID along with the process whose name contains the word "bash"
pids=$(pgrep -f bash)

# Loop through the PIDs and display the process name and PID
for pid in $pids; do
    name=$(tr '\0' ' ' < "/proc/$pid/cmdline" | sed 's/.$//')
    echo "$pid $name"
done
