#!/usr/bin/env bash
# superstitious numbers

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
	4)[ $i == 4 ]
		echo "bad luck from China"
		;;
	9)[ $i -eq 9 ]
		echo "bad luck from Japan"
		;;
	17)[ $i -eq 17 ]
		echo "bad luck from Italy"
		;;
	*) #
	esac

	(( i++ ))
done
