#!/usr/bin/env bash
# displays hour from one to 12 and min from 1 - 59

hour=0

while ((hour <= 12 ))
do
  echo "Hour: $hour"
  minute=1
  while ((minute <= 59))
  do
    echo "$minute"
    ((minute++))
  done
  ((hour++))
done
