#!/usr/bin/env bash
# displays time
minute=1
hour=0
echo "Hour: $hour"
while [ "$hour" -lt 12 ]
do
	while [ "$minute" -le 59 ]
	do 
		echo "$minute"
		minute=$((minute + 1))
	done
	hour=$((hour + 1))
	echo "Hour: $hour"
	minute=1
done
